server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: hotel-service
          uri: http://${HOTEL_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/hotels
            - Method=POST
          filters:
            - SetPath=/api/hotel
        - id: hotel-service-all
          uri: http://${HOTEL_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/hotels
            - Method=GET
          filters:
            - SetPath=/api/hotel/all
        - id: booking-service
          uri: http://${BOOKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/bookings
            - Method=POST
          filters:
            - SetPath=/api/booking
        - id: booking-service-delete
          uri: http://${BOOKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/bookings/{bookingNbr}
            - Method=DELETE
          filters:
            - SetPath=/api/booking/{bookingNbr}
        - id: booking-service-all
          uri: http://${BOOKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/bookings
            - Method=GET
          filters:
            - SetPath=/api/booking/all
        - id: customer-service-all
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/customers
            - Method=GET
          filters:
            - SetPath=/api/customer/all
        - id: customer-service-update
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/customers/{customerId}
            - Method=PUT
          filters:
            - SetPath=/api/customer/{customerId}
        - id: customer-service-find-by-id
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/customers/by-id/{customerId}
            - Method=GET
          filters:
            - SetPath=/api/customer/by-id/{customerId}